name: Publish

on: push

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Set homepage to avoid absolute links error
        run:  sed -z -r -i "s/\{/{\n  \"home\"\:\"\/$(echo {{ vars.GITHUB_REPOSITORY }} | grep -E -o '[^/]+$')\",/" package.json
      - name: Build
        run: npm i && npm run build
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ vars.GITHUB_REF_NAME }}
          publish_branch: 'deploy'
